-- =========================================================
-- FloodSense - Estrutura do Banco de Dados
-- Banco: PostgreSQL / Supabase
-- =========================================================

-- =====================
-- TABELA: usuario
-- =====================
CREATE TABLE public.usuario (
    id_usuario UUID PRIMARY KEY DEFAULT auth.uid(),
    data_cadastro TIMESTAMPTZ NOT NULL DEFAULT now(),
    nome VARCHAR NOT NULL,
    email VARCHAR NOT NULL UNIQUE,

    CONSTRAINT usuario_id_usuario_fkey
        FOREIGN KEY (id_usuario)
        REFERENCES auth.users(id)
);

-- =====================
-- TABELA: ocorrencia
-- =====================
CREATE TABLE public.ocorrencia (
    id_ocorrencia BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    data_hora TIMESTAMPTZ NOT NULL DEFAULT now(),
    id_usuario UUID NOT NULL,
    descricao TEXT,
    latitude NUMERIC NOT NULL,
    longitude NUMERIC NOT NULL,
    status VARCHAR NOT NULL DEFAULT 'REGISTRADA',

    CONSTRAINT ocorrencia_id_usuario_fkey
        FOREIGN KEY (id_usuario)
        REFERENCES public.usuario(id_usuario)
);

-- =====================
-- TABELA: imagem
-- =====================
CREATE TABLE public.imagem (
    id_imagem BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    data_captura TIMESTAMPTZ NOT NULL DEFAULT now(),
    id_ocorrencia BIGINT NOT NULL,
    caminho_imagem TEXT NOT NULL,

    CONSTRAINT imagem_id_ocorrencia_fkey
        FOREIGN KEY (id_ocorrencia)
        REFERENCES public.ocorrencia(id_ocorrencia)
);

-- =====================
-- TABELA: analise_ia
-- =====================
CREATE TABLE public.analise_ia (
    id_analise BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    data_analise TIMESTAMPTZ NOT NULL DEFAULT now(),
    id_ocorrencia BIGINT NOT NULL UNIQUE,
    resultado VARCHAR NOT NULL,
    classificacao VARCHAR NOT NULL,
    nivel_confianca NUMERIC,

    CONSTRAINT analise_ia_id_ocorrencia_fkey
        FOREIGN KEY (id_ocorrencia)
        REFERENCES public.ocorrencia(id_ocorrencia)
);

-- =====================
-- TABELA: encaminhamento
-- =====================
CREATE TABLE public.encaminhamento (
    id_encaminhamento BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    data_encaminhamento TIMESTAMPTZ NOT NULL DEFAULT now(),
    id_ocorrencia BIGINT NOT NULL UNIQUE,
    orgao_responsavel VARCHAR NOT NULL,
    status_encaminhamento VARCHAR NOT NULL DEFAULT 'SIMULADO',

    CONSTRAINT encaminhamento_id_ocorrencia_fkey
        FOREIGN KEY (id_ocorrencia)
        REFERENCES public.ocorrencia(id_ocorrencia)
);
